### ISSUE TITLE
Tool failed to recognize the state of a LUKS1 volume

### ISSUE THREAD

**Issue by Ricky-Tigg** [latchset/luksmeta#11]
OS: Fedora; Component: luksmeta.x86_64  9-5.fc31 @fedora

Hey. Tool failed to recognize the state of a LUKS1 volume. Surprisingly a tool dedicated to LUKS v2 volumes succeeded in that task.
```
# lsblk -o name,fstype,type,mode,mountpoint
NAME                                          FSTYPE      TYPE  MODE       MOUNTPOINT
[...]
└─sda6                                        crypto_LUKS part  brw-rw---- 
  └─luks-acf8855f-302b-4ea5-90f6-12a256deb1fa LVM2_member crypt brw-rw---- 
# cryptsetup luksDump /dev/sda6
[...]
Version:       	1
[...]
Key Slot 0: ENABLED
[...]
# luksmeta show -d /dev/sda6
Device is not initialized (/dev/sda6)
```

**Comment by sarroutbi** [comment]
According to luksmeta man page:

        The luksmeta utility enables an administrator to store metadata in the gap between the end of the LUKSv1 header and
        the start of the encrypted data. This is useful for storing data that is available before the volume is unlocked,
        usually for use during the volume unlock process.

       The metadata is stored in a series of UUID-typed slots, allowing multiple blocks of metadata. Although the luksmeta
       slots are inspired by the LUKS slots, they are functionally independent and share only a casual relationship. Slots
       merely provide a hint that a given chunk of metadata is associated with a specific LUKSv1 password (in a slot with
       the same number). However, luksmeta itself is indifferent to the relationship between a LUKSv1 slot and the
       correspondly numbered luksmeta slot, with one exception (detailed below).

       After a LUKSv1 volume is initialized using cryptsetup(8), it must also be initialized for metadata storage by
       luksmeta init. Once this is complete, the device is ready to store medata.

       Data can be written to a slot using luksmeta save or read from a slot using luksmeta load. You can also erase the
       data in an existing slot using luksmeta wipe or query the slots using luksmeta show.
       
**luksmeta show** will not dump information of metadata of a device if that device has not been initialized appropriately:

```
[user@fedora ~]$ fallocate -l64M ~/luks-device-v1
[user@fedora ~]$ cryptsetup luksDump ~/luks-device-v1 
Device /home/user/luks-device-v1 is not a valid LUKS device.
(failed reverse-i-search)`crupt': ^Cyptsetup luksDump ~/luks-device-v1 
[user@fedora ~]$ cryptsetup luksFormat --type "luks1" --force-password ~/luks-device-v1 

WARNING!
========
This will overwrite data on /home/sarroutb/luks-device-v1 irrevocably.

Are you sure? (Type 'yes' in capital letters): YES
Enter passphrase for /home/sarroutb/luks-device-v1: 
Verify passphrase: 
[user@fedora ~]$ cryptsetup luksFormat --type "luks1" --force-password ~/luks-device-v1 
[user@fedora ~]$ luksmeta show -d ~/luks-device-v1 
Device is not initialized (/home/sarroutb/luks-device-v1)
[user@fedora ~]$ luksmeta init -d ~/luks-device-v1 
You are about to initialize a LUKS device for metadata storage.
Attempting to initialize it may result in data loss if data was
already written into the LUKS header gap in a different format.
A backup is advised before initialization is performed.

Do you wish to initialize /home/sarroutb/luks-device-v1? [yn] y
[user@fedora ~]$ luksmeta show -d ~/luks-device-v1 
0   active empty
1 inactive empty
2 inactive empty
3 inactive empty
4 inactive empty
5 inactive empty
6 inactive empty
7 inactive empty
```

**Comment by Ricky-Tigg** [comment]
Onto a device already containing a 'crypto_LUKS' superblock signature i had been so far able to store data without relying on `fallocate -l64M` and `luksmeta init`  while my first command was:
`# cryptsetup luksFormat /dev/sdc1 --debug -v -c aes-xts-plain64 -h sha512 -s 512 -t 32 -T 8 --use-urandom -i 8192 --pbkdf argon2i --force-password --disable-keyring --integrity hmac-sha256 --label 0`

Does `fallocate -l64M` has to take place before the previous command?
Does that statement apply to LUKSv2 volume?
`After a LUKSv1 volume is initialized using cryptsetup(8), it must also be initialized for metadata storage byluksmeta init.`
